---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket configuration lake-formation'

###############################################################################
### Metadata
###############################################################################

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'pod data-plateforme '


###############################################################################
### Parameters
###############################################################################

Parameters:
  Environment:
    Description: Environment
    Default: prd
    Type: String

  Adminrole:
    Description: adminrole arn
    Default: role
    Type: String

  S3Stack:
    Description: stack resources S3
    Default: pod-dp-S3-creation
    Type: String

###############################################################################
### Resources
###############################################################################

Resources:
  Lakeformationsettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: !Sub '${Adminrole}'

  DatalakeLocationPrepared:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        'Fn::ImportValue': !Sub '${S3Stack}-prepared-arn'
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lakeformation.amazonaws.com/AWSServiceRoleForLakeFormationDataAccess
      UseServiceLinkedRole: true

  DatalakeLocationIncoming:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        'Fn::ImportValue': !Sub '${S3Stack}-incoming-arn'
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lakeformation.amazonaws.com/AWSServiceRoleForLakeFormationDataAccess
      UseServiceLinkedRole: true


  DatalakeLocationGold:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        'Fn::ImportValue': !Sub '${S3Stack}-gold-arn'
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lakeformation.amazonaws.com/AWSServiceRoleForLakeFormationDataAccess
      UseServiceLinkedRole: true


  DatalakeLocationSchema:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        'Fn::ImportValue': !Sub '${S3Stack}-schema-arn'
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lakeformation.amazonaws.com/AWSServiceRoleForLakeFormationDataAccess
      UseServiceLinkedRole: true


  DatalakeLocationRaw:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        'Fn::ImportValue': !Sub '${S3Stack}-raw-arn'
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lakeformation.amazonaws.com/AWSServiceRoleForLakeFormationDataAccess
      UseServiceLinkedRole: true


