---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket configuration Pod data-plateforme'

###############################################################################
### Parameters
###############################################################################

Parameters:
  Environment:
    Description: Environment
    Default: prd
    Type: String

###############################################################################
### Resources
###############################################################################

Resources:

  Raw:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pod-dp-${Environment}-raw'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Description
          Value: pod-dataplatform
    DeletionPolicy: Retain

  Prepared:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pod-dp-${Environment}-prepared'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Description
          Value: pod-dataplatform
    DeletionPolicy: Retain

  Gold:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pod-dp-${Environment}-gold'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Description
          Value: pod-dataplatform
    DeletionPolicy: Retain

  Schema:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pod-dp-${Environment}-schema'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Description
          Value: pod-dataplatform
    DeletionPolicy: Retain


  Artifacts:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pod-dp-${Environment}-artifacts'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Description
          Value: pod-dataplatform
    DeletionPolicy: Retain

  Toto:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pod-dp-${Environment}-toto'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Description
          Value: pod-dataplatform
    DeletionPolicy: Retain

###############################################################################
### Outputs
###############################################################################

Outputs:
  RawBucket:
    Description: Id of the raw bucket
    Value: !Ref Raw
    Export:
      Name: !Sub "${AWS::StackName}-raw"

  RawBucketArn:
    Description: Arn of the raw bucket
    Value: !GetAtt Raw.Arn
    Export:
      Name: !Sub "${AWS::StackName}-raw-arn"

  PreparedBucket:
    Description: Id of the Prepared bucket
    Value: !Ref Prepared
    Export:
      Name: !Sub "${AWS::StackName}-prepared"

  PreparedBucketArn:
    Description: Arn of the Prepared bucket
    Value: !GetAtt Prepared.Arn
    Export:
      Name: !Sub "${AWS::StackName}-prepared-arn"

  GoldBucket:
    Description: Id of the Gold bucket
    Value: !Ref Gold
    Export:
      Name: !Sub "${AWS::StackName}-gold"

  GoldBucketArn:
    Description: Arn of the Gold bucket
    Value: !GetAtt Gold.Arn
    Export:
      Name: !Sub "${AWS::StackName}-gold-arn"

  SchemaBucket:
    Description: Id of the Schema bucket
    Value: !Ref Schema
    Export:
      Name: !Sub "${AWS::StackName}-schema"

  SchemaBucketArn:
    Description: Arn of the Schema bucket
    Value: !GetAtt Schema.Arn
    Export:
      Name: !Sub "${AWS::StackName}-schema-arn"

  ArtifactsBucket:
    Description: Id of the Schema bucket
    Value: !Ref Artifacts
    Export:
      Name: !Sub "${AWS::StackName}-artifacts"

  ArtifactsBucketArn:
    Description: Arn of the Schema bucket
    Value: !GetAtt Artifacts.Arn
    Export:
      Name: !Sub "${AWS::StackName}-artifacts-arn"